### POST request to create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Barron Trump",
  "address": "No 412, Madison Street, Tucson, Arizona",
  "email": "barrontrump@gmail.com",
  "dateOfBirth": "2003-11-11",
  "registeredDate": "2022-09-12"
}
###