### POST request to create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Donald Trump",
  "address": "No 24, Bridge Street, Lowell, Massachusetts",
  "email": "magatrump@gmail.com",
  "dateOfBirth": "1951-11-11",
  "registeredDate": "2020-09-12"
}
###